### ISSUE TITLE
Implement Lidar ROS driver

### ISSUE THREAD

**Issue by vuquangtrong** [vuquangtrong/lidar-mapping#6]
The mapping process needs to do:
* Capture point-cloud from Lidar
* Align Position and Pose with point-cloud
* Process mapping

To-do:
* [ ] Run Lidar ROS driver and Subscribe to capture point-cloud, refer #1 
* [ ] Run GNSS driver and Subscribe to capture position, refer #4 
* [ ] Run IMU driver and Subscribe to capture pose, refer #5 
* [ ] Align data (point-cloud, position, and pose) using ROS timestamp
* [ ] Process mapping using point-cloud, position, and pose
* [ ] Publish mapped data , and save to file
    * [ ] Visualize mapped data on `rviz`
